### ISSUE TITLE
Pulsante Salvataggio

### ISSUE THREAD

**Issue by PorfirioTramontana** [Testing-Game-SAD-2023/A13#10]
Nella GUI il pulsante di salvataggio della classe di test non funziona poichè salva come file locale il template iniziale della classe di test e non lo stato attuale della classe di test che il giocatore ha iniziato a scrivere.

La classe di test è peraltro disponibile sul container, ma solo dopo una compilazione andata a buon fine e con successiva misura della copertura: le due funzionalità andrebbero in qualche modo collegate.

Probabilmente si potrebbe introdurre una funzione di salvataggio in remoto che vada a salvare sul volume la classe su richiesta (e non soltanto dopo la misura della copertura) e una di esportazione in locale che permetta di ottenere via http la classe precedentemente salvata

**Comment by reverse-unina** [comment]
Sembrerebbe che nelle ultime versionni, con un nuovo pulsante Download, funzioni.
