### ISSUE TITLE
Creazione modalità scalata non funzionante

### ISSUE THREAD

**Issue by HeineCantor** [Testing-Game-SAD-2023/A13#30]
Dopo la merge della Pull Request #26 non è più possibile giocare a una modalità Scalata.

**Comment by KateIvul** [comment]
@StefanoMarano80017, non so se ancora ci dovete lavorare/aggiustare...

**Comment by StefanoMarano80017** [comment]
Sì è ovvio che non funzioni, non funziona manco l'editor a questo commit, lo stiamo debuggando in questi giorni perchè la lista di cose da aggiustare era tendente all'infinito.
