### ISSUE TITLE
Problema con i pulsanti di ridimensionamento delle finestre

### ISSUE THREAD

**Issue by PorfirioTramontana** [Testing-Game-SAD-2023/A13#33]
**Describe the bug**
I frame Console e Results dell'interfaccia Editor possono essere allargati e ridotti. Dopo la prima riduzione, però, il loro allargamento si limita ad una sola riga dalla quale non è possibile leggere il testo contenuto nel frame

**To Reproduce**
1. Go to Code Editor (modalità partita Singola)
2. Click su pulsante di RIduzione Frame Console
3. Click su pulsante di Ingrandimento Frame Console
4. La finestra Console rimane minimizzata e non è possibile leggerne il contenuto

**Expected behavior**
La finestra console sarebbe giusto che possa essere ridimensionata liberamente ad una qualsiasi dimensione. In alternativa, una dimensione a mezzo schermo sarebbe comunque accettabile

**Screenshots**
Schermata ottenuta al passo 4.
<img width="475" alt="image" src="https://github.com/user-attachments/assets/27bb6fae-0c53-44e1-80bf-195e6a71ce97">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome 129.0.6668.90
 - Commit Version 5e155762c9305729ea4d3677beaec8ef4b83aa80

**Comment by reverse-unina** [comment]
Il pulsante di ridimensionamento va utilizzato in modalità drag and drop
