### ISSUE TITLE
Problema in fase di installazione manvsclass

### ISSUE THREAD

**Issue by PorfirioTramontana** [Testing-Game-SAD-2023/A13#34]
**Describe the bug**
Installando il commit [5519899](https://github.com/Testing-Game-SAD-2023/A13/commit/551989981ebbc18f1bad04085e41a74b4da89db0) su di una macchina nella quale precedentemente il sistema funzionava, ora l'installazione di ferma a manvsclass

**To Reproduce**
1. Esegui uninstaller.bat
2. Esegui installer.bat
3. Viene dichiarato il seguente errore: [ERROR] Failed to execute goal on project manvsclass: Could not resolve dependencies for project com.groom:manvsclass:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: com.commons:commons:jar:1.0-SNAPSHOT (absent): Could not find artifact com.commons:commons:jar:1.0-SNAPSHOT -> [Help 1]

**Screenshots**
![image](https://github.com/user-attachments/assets/6954fd01-a4cd-4cae-99f0-241b7e522d20)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Docker Version 4.34.3

**Comment by HeineCantor** [comment]
C'è stato un refuso in una merge recente nel pom.xml di _manvsclass_ e _t5_. Adesso dovrebbe essere inclusa la dipendenza da _commons_ all'interno dei pom. 

È importante però compilare il modulo _commons_ tramite Maven prima di compilare tutti gli altri.

**Comment by PorfirioTramontana** [comment]
Ho riprovato oggi con il commit [3f7a048](https://github.com/Testing-Game-SAD-2023/A13/commit/3f7a0485bc6e38b587c2cc8b04ca1b27167bfdd3) e il problema si ripropone in maniera identica.

**Comment by PorfirioTramontana** [comment]
Non ho capito se la compilazione del modulo common con Maven è compresa nella procedura di installazione e, se non lo fosse, come mai non sia compresa e in quale contesta possa essere eseguita.

**Comment by HeineCantor** [comment]
Può provare ora? Purtroppo sto su Linux e nell'aggiornamento mi sono perso di aggiornare il file bat

**Comment by PorfirioTramontana** [comment]
Ho riprovato ma c'è ancora lo stesso errore e ho dovuto manualmente eseguire il mvn install (commit 
[76e7c4e](https://github.com/Testing-Game-SAD-2023/A13/commit/76e7c4e2d04b455b346435b57bf7c8b968442163) )

**Comment by PorfirioTramontana** [comment]
Riprovato su un'altra macchina con configurazione simile e c'è di nuovo un problema bloccante per l'installazione, relativo all'ultima dipendenza da commons aggiunta.

La dipendenza da com.commons non viene risolta (forse prima veniva risolta fortunosamente perchè già disponibile su questa macchina). Come risolvere in una soluzione generale?

"Calling function # 1:"
"Installing T1-G11"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------< com.groom:manvsclass >------------------------
[INFO] Building manvsclass 0.0.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.commons:commons:jar:1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.631 s
[INFO] Finished at: 2024-10-29T14:44:33+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project manvsclass: Could not resolve dependencies for project com.groom:manvsclass:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: com.commons:commons:jar:1.0-SNAPSHOT (absent): Could not find artifact com.commons:commons:jar:1.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
